let editing=null,loadedApplication=null;
const BASE="https://asia-south1-jain-community-platform.cloudfunctions.net";
const call=async(name,data)=>{const r=await fetch(BASE+"/"+name,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({data})});const j=await r.json();if(!r.ok||j.error)throw new Error(j.error?.message||"सेवा उपलब्ध नहीं है।");return j.data};
let config={},rules=[];
const $=id=>document.getElementById(id);
function escapeHtml(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
function formMsg(t,type="error"){const e=$("formMessage");e.textContent=t;e.className="msg "+type;e.classList.remove("hidden")}
function clearFormMsg(){$("formMessage").classList.add("hidden")}
async function load(){try{const r=await call("pratibhaConfig",{});config=r.config;rules=r.rules;$("description").textContent=config.description||"";$("window").innerHTML="<div class=datebox>फॉर्म: "+(config.enabled?"चालू":"बंद")+"</div><div class=datebox>अंतिम तिथि: "+(config.registrationLastDate||"निर्धारित नहीं")+"</div><div class=datebox>कार्यक्रम: "+(config.eventDate||"निर्धारित नहीं")+"</div>";$("rules").innerHTML=rules.length?rules.map(x=>'<label><input type="checkbox" data-rule="'+escapeHtml(x.id)+'"> '+escapeHtml(x.hindi)+'</label>').join(""):"<p>अभी कोई नियम उपलब्ध नहीं है।";if(config.enabled===false)$("findRegistration").disabled=true}catch(e){$("lookupMessage").innerHTML='<div class="msg error">'+escapeHtml(e.message)+"</div>"}}
function compress(file){return new Promise((resolve,reject)=>{if(!file)return resolve(null);if(file.type==="application/pdf"){if(file.size>5*1024*1024)return reject(new Error("PDF 5 MB से छोटा होना चाहिए।"));const rd=new FileReader();rd.onload=()=>resolve({name:file.name,mimeType:file.type,base64:rd.result});rd.onerror=reject;rd.readAsDataURL(file);return}const im=new Image();im.onload=()=>{const max=1400,scale=Math.min(1,max/Math.max(im.width,im.height)),c=document.createElement("canvas");c.width=Math.round(im.width*scale);c.height=Math.round(im.height*scale);c.getContext("2d").drawImage(im,0,0,c.width,c.height);c.toBlob(blob=>{if(!blob)return reject(new Error("फोटो तैयार नहीं हो सका।"));const rd=new FileReader();rd.onload=()=>resolve({name:file.name,mimeType:"image/jpeg",base64:rd.result});rd.onerror=reject;rd.readAsDataURL(blob)},"image/jpeg",.78)};im.onerror=reject;im.src=URL.createObjectURL(file)})}
function preview(input,target){input.addEventListener("change",()=>{const f=input.files[0];if(!f)return;target.src=URL.createObjectURL(f);target.classList.remove("hidden")})}
function showForm(application,mobileNumber){editing=application?{applicationId:application.applicationId,accessToken:localStorage.getItem("ps26-token:"+application.applicationId)||""}:null;loadedApplication=application||null;$("newRegistration").classList.remove("hidden");$("lookupCard").classList.add("hidden");$("formTitle").textContent=application?"आवेदन संपादित करें":"नया आवेदन";$("submit").textContent=application?"संशोधित आवेदन जमा करें":"आवेदन जमा करें";$("cancelEdit").classList.remove("hidden");const form=$("form");if(application){for(const [k,v] of Object.entries(application)){const el=form.querySelector("[name="+k+"]");if(el&&typeof v==="string")el.value=v}document.querySelectorAll("[data-rule]").forEach(x=>x.checked=true);$("facePhoto").required=false}else{form.reset();form.querySelector('[name="mobile"]').value=mobileNumber;$("facePhoto").required=true;document.querySelectorAll("[data-rule]").forEach(x=>x.checked=false)}window.scrollTo({top:0,behavior:"smooth"})}
function resetToLookup(){editing=null;loadedApplication=null;$("form").reset();$("newRegistration").classList.add("hidden");$("lookupCard").classList.remove("hidden");$("existingRegistration").classList.add("hidden");$("lookupMessage").innerHTML="";$("lookupMobile").value=""}
preview($("facePhoto"),$("facePreview"));$("documents").addEventListener("change",()=>{$("docCount").textContent=$("documents").files.length+" दस्तावेज़ चुने गए।"});$("cancelEdit").onclick=resetToLookup;
$("findRegistration").onclick=async()=>{try{const mobile=$("lookupMobile").value.replace(/\D/g,"");if(!/^[6-9]\d{9}$/.test(mobile))throw new Error("कृपया सही 10 अंकों का मोबाइल नंबर दर्ज करें।");$("findRegistration").disabled=true;$("lookupMessage").innerHTML='<div class="msg info">पंजीकरण खोजा जा रहा है...</div>';const r=await call("pratibhaFindByMobile",{mobileNumber:mobile});if(!r.found){$("existingRegistration").classList.add("hidden");$("lookupMessage").innerHTML='<div class="msg success">इस मोबाइल नंबर से कोई पंजीकरण नहीं मिला। नया आवेदन शुरू करें।</div><div class="actions" style="justify-content:center"><button class="button primary" id="createNew" type="button">नया आवेदन शुरू करें</button></div>';$("createNew").onclick=()=>showForm(null,mobile);return}localStorage.setItem("ps26-token:"+r.application.applicationId,r.accessToken);const a=r.application;$("lookupMessage").innerHTML='<div class="msg success">आपका पंजीकरण मिल गया है। नीचे विवरण देखें और आवश्यकता होने पर संपादित करें।</div>';$("existingRegistration").classList.remove("hidden");$("existingRegistration").innerHTML='<h3>मौजूदा पंजीकरण</h3><div class="summary"><div><b>आवेदन क्रमांक</b><br>'+escapeHtml(a.applicationId)+'</div><div><b>स्थिति</b><br>'+escapeHtml(a.status)+'</div><div><b>नाम</b><br>'+escapeHtml(a.name)+'</div><div><b>मोबाइल</b><br>'+escapeHtml(a.mobile)+'</div><div><b>विद्यालय</b><br>'+escapeHtml(a.schoolInstitute)+'</div><div><b>कक्षा</b><br>'+escapeHtml(a.classStandard)+'</div><div><b>माता</b><br>'+escapeHtml(a.motherName)+'</div><div><b>पिता</b><br>'+escapeHtml(a.fatherName)+'</div><div><b>जन्म तिथि</b><br>'+escapeHtml(a.dateOfBirth)+'</div></div><p><b>पता:</b> '+escapeHtml(a.address)+', '+escapeHtml(a.city)+', '+escapeHtml(a.state)+' - '+escapeHtml(a.pincode)+'</p><p><b>उपलब्धि:</b> '+escapeHtml(a.achievementDetails)+'</p><div class="actions"><button class="button primary" id="editExisting" type="button">आवेदन संपादित करें</button></div>';if(["CONSIDERED_FOR_SAMMAN","NOT_SELECTED"].includes(a.status)){$("editExisting").disabled=true;$("editExisting").textContent="आवेदन अंतिम रूप से तय हो चुका है"}$("editExisting").onclick=()=>showForm(a,mobile)}catch(e){const t=e.message==="Failed to fetch"?"सेवा अभी उपलब्ध नहीं है। कृपया कुछ देर बाद पुनः प्रयास करें।":e.message;$("lookupMessage").innerHTML='<div class="msg error">'+escapeHtml(t)+"</div>"}finally{$("findRegistration").disabled=false}};
$("form").addEventListener("submit",async e=>{e.preventDefault();try{$("submit").disabled=true;clearFormMsg();formMsg("आवेदन सुरक्षित किया जा रहा है...","info");const f=new FormData(e.target),d=Object.fromEntries(f.entries());const docs=[...$("documents").files];if(docs.length>10)throw new Error("अधिकतम 10 दस्तावेज़ चुनें।");const face=await compress($("facePhoto").files[0]);if(editing&&face)d.facePhoto=face;else if(face)d.facePhoto=face;else if(!editing)throw new Error("कृपया चेहरे का फोटो चुनें।");d.supportingDocuments=[];for(const file of docs)d.supportingDocuments.push(await compress(file));d.acceptedRuleIds=[...document.querySelectorAll("[data-rule]:checked")].map(x=>x.dataset.rule);if(d.acceptedRuleIds.length!==rules.length)throw new Error("कृपया सभी नियम स्वीकार करें।");let r;if(editing){if(!editing.accessToken)throw new Error("इस आवेदन को संपादित करने की अनुमति उपलब्ध नहीं है। कृपया मोबाइल नंबर से फिर से खोजें।");r=await call("pratibhaUpdate",{...d,applicationId:editing.applicationId,accessToken:editing.accessToken})}else{r=await call("pratibhaCreate",d);localStorage.setItem("ps26-token:"+r.application.applicationId,r.accessToken)}$("newRegistration").innerHTML='<div class="success-panel ps-card"><h2>✓ आवेदन सफलतापूर्वक सुरक्षित हो गया</h2><p>'+(editing?"आपका संशोधित आवेदन पुनः समीक्षा के लिए भेज दिया गया है।":"आपका आवेदन सफलतापूर्वक जमा हो गया है।")+'</p><p>आपका आवेदन क्रमांक:</p><div class="app-number">'+escapeHtml(editing?editing.applicationId:r.application.applicationId)+'</div><p class="muted">इस मोबाइल नंबर से दोबारा खोजकर आप अपना आवेदन देख सकते हैं और उपलब्ध होने पर संपादित कर सकते हैं।</p><div class="actions" style="justify-content:center"><button class="button primary" type="button" id="done">ठीक है</button></div></div>';$("done").onclick=resetToLookup;editing=null}catch(err){formMsg(err.message,"error");window.scrollTo({top:$("newRegistration").offsetTop-20,behavior:"smooth"})}finally{$("submit").disabled=false}});
$("lookupMobile").addEventListener("keydown",e=>{if(e.key==="Enter")$("findRegistration").click()});
load();
