const KSHAMAWANI_CONFIG="data/kshamawani-2026.json";
document.addEventListener("DOMContentLoaded",async()=>{
 const form=document.getElementById("kshamawani-form"),message=document.getElementById("form-message"),button=document.getElementById("submit-button"),success=document.getElementById("success-section"),intro=document.getElementById("intro"),instruction=document.getElementById("venue-instruction");
 let config;
 const showMessage=t=>{message.textContent=t;message.classList.remove("hidden")},clearMessage=()=>{message.textContent="";message.classList.add("hidden")};
 const cleanMobile=v=>String(v||"").replace(/\D/g,"");
 const validate=d=>{if(!d.name.trim())return"कृपया नाम दर्ज करें।";if(!d.address.trim())return"कृपया पूरा पता दर्ज करें।";if(!/^[6-9]\d{9}$/.test(d.mobile))return"कृपया सही 10 अंकों का मोबाइल नंबर दर्ज करें।";if(!Number.isInteger(d.coupons)||d.coupons<1||d.coupons>config.registration.maxCoupons)return"कृपया कूपन की सही संख्या दर्ज करें।";return null};
 const qr=(code,mobile)=>{const h=document.getElementById("qr-code");h.innerHTML="";if(typeof window.qrcode!=="function"){showMessage("QR कोड तैयार नहीं हो सका। कृपया पुनः प्रयास करें।");return}const q=window.qrcode(0,"M");q.addData(JSON.stringify({v:1,eventId:config.id,applicationCode:code,mobile}));q.make();h.innerHTML=q.createSvgTag({scalable:true,margin:4})};
 const showSuccess=r=>{const code=r.registrationId||r.applicationCode;document.getElementById("application-code").textContent=code||"—";document.getElementById("success-summary").textContent=`${r.name||"आवेदक"} के लिए ${r.coupons||1} भोजन कूपन दर्ज किए गए हैं।`;qr(code,r.mobile);instruction.textContent=config.messages.venueInstruction;form.classList.add("hidden");success.classList.remove("hidden");window.scrollTo({top:0,behavior:"smooth"})};
 const lookup=mobile=>new Promise((resolve,reject)=>{const cb="kwLookup_"+Date.now()+"_"+Math.random().toString(36).slice(2),s=document.createElement("script"),timeout=setTimeout(()=>{cleanup();reject(new Error("सर्वर से प्रतिक्रिया नहीं मिली।"))},15000);function cleanup(){clearTimeout(timeout);delete window[cb];s.remove()}window[cb]=r=>{cleanup();resolve(r)};s.onerror=()=>{cleanup();reject(new Error("पंजीकरण सेवा से संपर्क नहीं हो सका।"))};s.src=`${config.registration.apiUrl}?api=lookupRegistration&eventId=${encodeURIComponent(config.id)}&mobile=${encodeURIComponent(mobile)}&callback=${cb}`;document.body.appendChild(s)});
 const submit=d=>new Promise((resolve,reject)=>{const n="kwSubmit_"+Date.now(),iframe=document.createElement("iframe");iframe.name=n;iframe.hidden=true;document.body.appendChild(iframe);const node=document.createElement("form");node.method="POST";node.action=config.registration.apiUrl;node.target=n;node.hidden=true;const input=document.createElement("input");input.type="hidden";input.name="payload";input.value=JSON.stringify({action:"createRegistration",data:{eventId:config.id,mobile:d.mobile,name:d.name.trim(),address:d.address.trim(),coupons:d.coupons,foodRequired:true,consentAccepted:true}});node.appendChild(input);document.body.appendChild(node);const timeout=setTimeout(()=>{cleanup();reject(new Error("सर्वर से प्रतिक्रिया मिलने में अधिक समय लग रहा है।"))},20000);function cleanup(){clearTimeout(timeout);node.remove();iframe.remove()}iframe.onload=()=>{cleanup();resolve({success:true})};node.submit()});
 try{const r=await fetch(KSHAMAWANI_CONFIG,{cache:"no-store"});if(!r.ok)throw Error();config=await r.json();intro.textContent=config.messages.intro}catch{showMessage("फॉर्म की जानकारी लोड नहीं हो सकी। कृपया पृष्ठ पुनः खोलें।");return}
 form.addEventListener("submit",async e=>{e.preventDefault();clearMessage();const d={name:document.getElementById("name").value,address:document.getElementById("address").value,mobile:cleanMobile(document.getElementById("mobile").value),coupons:Number(document.getElementById("coupons").value)},err=validate(d);if(err){showMessage(err);return}button.disabled=true;button.textContent="पंजीकरण हो रहा है...";try{const existing=await lookup(d.mobile);if(existing?.success&&existing.exists)throw new Error("इस मोबाइल नंबर से पहले ही पंजीकरण दर्ज है। आवश्यकता हो तो समन्वयक से संपर्क करें।");await submit(d);const saved=await lookup(d.mobile);if(!saved?.success||!saved.exists)throw new Error("पंजीकरण सुरक्षित होने की पुष्टि नहीं हो सकी।");showSuccess(saved.registration)}catch(error){showMessage(error.message||"पंजीकरण सुरक्षित नहीं हो सका। कृपया पुनः प्रयास करें।")}finally{button.disabled=false;button.textContent="पंजीकरण करें"}});
 document.getElementById("print-button").addEventListener("click",()=>window.print());
});