const { Buffer } = require("node:buffer");
const crypto = require("node:crypto");
const { FieldValue } = require("firebase-admin/firestore");
const { getStorage } = require("firebase-admin/storage");

const STORAGE_BUCKET = "jain-community-platform.firebasestorage.app";

const APPS="pratibhaSammanApplications", CFG="pratibhaSammanConfig", RULES="pratibhaSammanRules";
const DEFAULT_RULES=[
  {id:"pratibha-batch-2025-26",hindi:"यह सम्मान २०२५-२६ शैक्षणिक सत्र के विद्यार्थियों के लिए है।",displayOrder:1,active:true},
  {id:"pratibha-pune-eligibility",hindi:"उम्मीदवार पुणे का होना चाहिए और स्कूल भी पुणे में होना चाहिए।",displayOrder:2,active:true},
  {id:"pratibha-minimum-80-percent",hindi:"न्यूनतम कुल अंक 80% या उससे अधिक होने चाहिए।",displayOrder:3,active:true},
  {id:"pratibha-grade-mapping",hindi:"ग्रेडिंग प्रणाली होने पर ग्रेड और अंकों का समतुल्य मानचित्र आवेदन के साथ देना होगा।",displayOrder:4,active:false},
  {id:"pratibha-top-50",hindi:"केवल शीर्ष 50 पात्र बच्चों को सम्मानित किया जाएगा।",displayOrder:5,active:false},
  {id:"pratibha-tie-breaker",hindi:"टाई होने पर उम्मीदवारों के प्रत्येक विषय के अंकों की तुलना की जाएगी।",displayOrder:6,active:false},
  {id:"pratibha-attendance",hindi:"उम्मीदवार का पुरस्कार समारोह में उपस्थित होना आवश्यक है। रिश्तेदार उसकी ओर से पुरस्कार नहीं ले सकता।",displayOrder:7,active:true},
];
const MAX_DOCS=10, MAX_IMG=3*1024*1024, MAX_FILE=5*1024*1024;
const MIME=new Set(["image/jpeg","image/png","image/webp","application/pdf"]);
const hash=v=>crypto.createHash("sha256").update(String(v||"")).digest("hex");
const mobile=v=>{let x=String(v||"").replace(/\D/g,"");if(x.length===12&&x.startsWith("91"))x=x.slice(2);return x};
const date=v=>{if(!v)return "";const d=v?.toDate?v.toDate():new Date(v);return Number.isNaN(d.getTime())?"":d.toISOString()};
const admin=(key,expected)=>{if(!expected||!key||key!==expected)throw new Error("Unauthorized.")};
const config=async db=>{const s=await db.collection(CFG).doc("current").get();return s.exists?s.data():{enabled:true,opensAt:"",registrationLastDate:"",eventDate:"2026-10-25",title:"प्रतिभा सम्मान २०२६",description:"प्रतिभाशाली विद्यार्थियों के सम्मान के लिए आवेदन"}};
const rules=async db=>{
  let snap=await db.collection(RULES).get();
  if(snap.empty){
    await Promise.all(DEFAULT_RULES.map(r=>db.collection(RULES).doc(r.id).set({...r,updatedAt:FieldValue.serverTimestamp()},{merge:true})));
    snap=await db.collection(RULES).get();
  }else{
    const existing=new Map(snap.docs.map(d=>[d.id,d.data()]));
    const updates=[];
    for(const r of DEFAULT_RULES){
      if(!existing.has(r.id)){
        updates.push(db.collection(RULES).doc(r.id).set({...r,updatedAt:FieldValue.serverTimestamp()},{merge:true}));
      }
    }
    const legacyPune=existing.get("pratibha-pune-eligibility");
    if(legacyPune?.hindi==="केवल पुणे के विद्यार्थी पात्र हैं。"){
      updates.push(db.collection(RULES).doc("pratibha-pune-eligibility").update({hindi:"उम्मीदवार पुणे का होना चाहिए और स्कूल भी पुणे में होना चाहिए。",displayOrder:2,active:true,updatedAt:FieldValue.serverTimestamp()}));
    }
    if(updates.length) await Promise.all(updates);
    snap=await db.collection(RULES).get();
  }
  return snap.docs.map(d=>({id:d.id,...d.data()})).filter(r=>r.active!==false).sort((a,b)=>Number(a.displayOrder||0)-Number(b.displayOrder||0));
};
function windowOpen(c){if(c.enabled===false)throw new Error("Form submission is currently paused.");const n=Date.now();if(c.opensAt&&n<new Date(c.opensAt).getTime())throw new Error("Form submission has not opened yet.");if(c.registrationLastDate&&n>new Date(c.registrationLastDate).getTime())throw new Error("Registration is closed.")}
function validate(d, requireMedia=true){for(const k of ["name","mobile","address","city","state","pincode","motherName","fatherName","dateOfBirth","classStandard","schoolInstitute","achievementDetails","overallPercentage"])if(!String(d[k]||"").trim())throw new Error("Required field missing: "+k);d.mobile=mobile(d.mobile);if(!/^[6-9]\d{9}$/.test(d.mobile))throw new Error("Invalid mobile number.");if(!/^\d{6}$/.test(String(d.pincode)))throw new Error("Invalid PIN code.");const cls=String(d.classStandard||"").trim();if(!["10","12"].includes(cls))throw new Error("कक्षा केवल 10वीं या 12वीं हो सकती है।");const p=Number(d.overallPercentage);if(!Number.isFinite(p)||p<0||p>100)throw new Error("Overall percentage must be between 0 and 100.");const min=cls==="10"?85:80;if(p<min)throw new Error(`कक्षा ${cls}वीं के लिए न्यूनतम ${min}% आवश्यक है।`);d.overallPercentage=p;if(requireMedia&&!d.facePhoto)throw new Error("Face photo is required.");const docs=d.supportingDocuments||[];if(docs.length>MAX_DOCS)throw new Error("Maximum 10 supporting documents are allowed.");if(requireMedia){const aadhaar=docs.filter(x=>String(x.documentType||"").toUpperCase()==="AADHAAR").length;const marksheet=docs.filter(x=>String(x.documentType||"").toUpperCase()==="MARKSHEET").length;if(aadhaar!==1||marksheet!==1)throw new Error("एक Aadhaar और एक marksheet अनिवार्य है।");}return d}
async function nextId(db){return db.runTransaction(async tx=>{const r=db.doc("pratibhaSammanMeta/counter"),s=await tx.get(r),n=(s.exists?Number(s.data().value||0):0)+1;tx.set(r,{value:n,updatedAt:FieldValue.serverTimestamp()},{merge:true});return "PS26-"+String(n).padStart(5,"0")})}
async function upload(f,id,type){if(!f?.base64)throw new Error("Invalid upload.");if(!MIME.has(f.mimeType))throw new Error("Unsupported file type.");const raw=String(f.base64).replace(/^data:[^;]+;base64,/,""),b=Buffer.from(raw,"base64"),max=f.mimeType==="application/pdf"?MAX_FILE:MAX_IMG;if(!b.length||b.length>max)throw new Error("File is too large.");const ext=f.mimeType==="application/pdf"?"pdf":f.mimeType.split("/")[1],path=`pratibha-samman/${id}/${type}-${crypto.randomBytes(5).toString("hex")}.${ext}`;await getStorage().bucket(STORAGE_BUCKET).file(path).save(b,{metadata:{contentType:f.mimeType,cacheControl:"private,max-age=300"}});return{path,name:String(f.name||"upload").slice(0,100),mimeType:f.mimeType,size:b.length}}
async function url(path){if(!path)return "";const host=process.env.FIREBASE_STORAGE_EMULATOR_HOST;if(host){const bucket=getStorage().bucket(STORAGE_BUCKET).name;return "http://"+host+"/v0/b/"+encodeURIComponent(bucket)+"/o/"+encodeURIComponent(path)+"?alt=media"}const [u]=await getStorage().bucket(STORAGE_BUCKET).file(path).getSignedUrl({action:"read",expires:Date.now()+15*60*1000});return u}
async function media(a){const x={...a};for(const k of ["facePhoto","certificatePhoto"])if(x[k]?.path)x[k]={...x[k],url:await url(x[k].path)};x.supportingDocuments=await Promise.all((x.supportingDocuments||[]).map(async f=>({...f,url:await url(f.path)})));return x}
function pub(d){return{applicationId:d.applicationId,status:d.status,name:d.name,mobile:d.mobile,email:d.email||"",address:d.address,city:d.city,state:d.state,pincode:d.pincode,motherName:d.motherName,fatherName:d.fatherName,dateOfBirth:d.dateOfBirth,classStandard:d.classStandard,schoolInstitute:d.schoolInstitute,achievementDetails:d.achievementDetails,otherAccomplishments:d.otherAccomplishments||"",overallPercentage:d.overallPercentage??null,facePhoto:d.facePhoto||null,certificatePhoto:d.certificatePhoto||null,supportingDocuments:d.supportingDocuments||[],review:d.review||null,clarification:d.clarification||"",createdAt:date(d.createdAt),updatedAt:date(d.updatedAt),submittedAt:date(d.submittedAt)}}
async function createApplication({db,data}){const d=validate({...data}),c=await config(db);windowOpen(c);const existing=await db.collection(APPS).where("mobile","==",d.mobile).limit(1).get();if(!existing.empty)throw new Error("A registration already exists for this mobile number. Please search the existing registration and edit it.");const rs=await rules(db);if(!Array.isArray(d.acceptedRuleIds)||rs.some(r=>!d.acceptedRuleIds.includes(r.id)))throw new Error("All active rules must be accepted.");const id=await nextId(db),token=crypto.randomBytes(24).toString("hex"),face=await upload(d.facePhoto,id,"face"),docs=[];for(const f of d.supportingDocuments||[])docs.push(await upload(f,id,"document"));const record={applicationId:id,accessTokenHash:hash(token),name:String(d.name).trim(),mobile:d.mobile,email:String(d.email||"").trim(),address:String(d.address).trim(),city:String(d.city).trim(),state:String(d.state).trim(),pincode:String(d.pincode),motherName:String(d.motherName).trim(),fatherName:String(d.fatherName).trim(),dateOfBirth:String(d.dateOfBirth),classStandard:String(d.classStandard).trim(),schoolInstitute:String(d.schoolInstitute).trim(),achievementDetails:String(d.achievementDetails).trim(),otherAccomplishments:String(d.otherAccomplishments||"").trim(),overallPercentage:d.overallPercentage,facePhoto:face,supportingDocuments:docs,acceptedRulesSnapshot:rs.map(r=>({id:r.id,text:r.hindi})),status:"SUBMITTED",review:null,clarification:"",createdAt:FieldValue.serverTimestamp(),updatedAt:FieldValue.serverTimestamp(),submittedAt:FieldValue.serverTimestamp()};await db.collection(APPS).doc(id).set(record);return{application:pub(record),accessToken:token}}
async function authApp(db,id,token){const s=await db.collection(APPS).doc(String(id||"")).get();if(!s.exists)throw new Error("Application not found.");if(hash(token)!==s.data().accessTokenHash)throw new Error("Unauthorized.");return{s,data:s.data()}}
async function findApplicationByMobile({db,mobileNumber}){const normalized=mobile(mobileNumber);if(!/^[6-9]\d{9}$/.test(normalized))throw new Error("Invalid mobile number.");const snap=await db.collection(APPS).where("mobile","==",normalized).limit(2).get();if(snap.empty)return{found:false};if(snap.size>1)throw new Error("Multiple registrations found for this mobile number. Please contact the coordinator.");const data=snap.docs[0].data();const token=crypto.randomBytes(24).toString("hex");await snap.docs[0].ref.update({accessTokenHash:hash(token),updatedAt:FieldValue.serverTimestamp()});return{found:true,accessToken:token,application:await media(pub(data))}}
async function getApplication({db,applicationId,accessToken}){const{data}=await authApp(db,applicationId,accessToken);return{application:await media(pub(data))}}
async function updateApplication({db,applicationId,accessToken,data}){const{data:old}=await authApp(db,applicationId,accessToken);if(["CONSIDERED_FOR_SAMMAN","NOT_SELECTED"].includes(old.status))throw new Error("Finalized applications cannot be edited.");const d=validate({...data}, false),c=await config(db);windowOpen(c);const rs=await rules(db);if(!Array.isArray(d.acceptedRuleIds)||rs.some(r=>!d.acceptedRuleIds.includes(r.id)))throw new Error("All active rules must be accepted.");const face=d.facePhoto?await upload(d.facePhoto,applicationId,"face"):old.facePhoto,docs=[];if(Array.isArray(d.supportingDocuments)&&d.supportingDocuments.length){for(const f of d.supportingDocuments)docs.push(await upload(f,applicationId,"document"));}else{docs.push(...(old.supportingDocuments||[]));}await db.collection(APPS).doc(applicationId).update({...d,name:String(d.name).trim(),mobile:d.mobile,facePhoto:face,supportingDocuments:docs,acceptedRulesSnapshot:rs.map(r=>({id:r.id,text:r.hindi})),overallPercentage:d.overallPercentage,review:null,clarification:"",status:"SUBMITTED",updatedAt:FieldValue.serverTimestamp(),submittedAt:FieldValue.serverTimestamp(),accessTokenHash:old.accessTokenHash});return{success:true,status:"SUBMITTED"}}
async function adminList({db,accessKey,expectedKey,status="",filter=""}){admin(accessKey,expectedKey);const s=await db.collection(APPS).limit(500).get(),k=String(filter||"").toLowerCase().trim(),r=s.docs.map(d=>pub(d.data())).filter(a=>(!status||a.status===status)&&(!k||[a.applicationId,a.name,a.mobile,a.city,a.schoolInstitute].some(v=>String(v||"").toLowerCase().includes(k)))).sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt)));return{records:r,total:r.length}}
async function adminGet({db,accessKey,expectedKey,applicationId}){admin(accessKey,expectedKey);const s=await db.collection(APPS).doc(applicationId).get();if(!s.exists)throw new Error("Application not found.");return{application:await media(s.data())}}
async function downloadMedia({db,accessKey,expectedKey,applicationId,path}){admin(accessKey,expectedKey);const s=await db.collection(APPS).doc(String(applicationId||"")).get();if(!s.exists)throw new Error("Application not found.");const a=s.data(),allowed=[a.facePhoto?.path,...(a.supportingDocuments||[]).map(f=>f.path)].filter(Boolean);if(!path||!allowed.includes(path))throw new Error("Media access denied.");const file=getStorage().bucket(STORAGE_BUCKET).file(path),[exists]=await file.exists();if(!exists)throw new Error("Media not found.");const [buffer]=await file.download(),[metadata]=await file.getMetadata();return{buffer,contentType:metadata.contentType||"application/octet-stream",name:metadata.name||path.split("/").pop()}}
async function stats({db,accessKey,expectedKey}){admin(accessKey,expectedKey);const s=await db.collection(APPS).get(),r={total:s.size,needsReview:0,selected:0,rejected:0,notSelected:0};s.forEach(d=>{const x=d.data().status;if(["SUBMITTED","UNDER_REVIEW","CLARIFICATION_REQUIRED"].includes(x))r.needsReview++;if(x==="CONSIDERED_FOR_SAMMAN")r.selected++;if(x==="REJECTED")r.rejected++;if(x==="NOT_SELECTED")r.notSelected++});return r}
async function review({db,accessKey,expectedKey,applicationId,status,overallPercentage,score,comment,clarification}){admin(accessKey,expectedKey);if(!["UNDER_REVIEW","CONSIDERED_FOR_SAMMAN","NOT_SELECTED","CLARIFICATION_REQUIRED","REJECTED"].includes(status))throw new Error("Invalid review status.");const p=overallPercentage===""||overallPercentage==null?null:Number(overallPercentage);const s=score===""||score==null?null:Number(score);if(s!=null&&(!Number.isInteger(s)||s<1||s>5))throw new Error("Score must be between 1 and 5.");if(p!=null&&(!Number.isFinite(p)||p<0||p>100))throw new Error("Percentage must be between 0 and 100.");await db.collection(APPS).doc(applicationId).update({status,overallPercentage:p,review:{score:s,comment:String(comment||"").slice(0,3000),clarification:String(clarification||"").slice(0,3000),reviewedAt:FieldValue.serverTimestamp()},clarification:String(clarification||"").slice(0,3000),updatedAt:FieldValue.serverTimestamp()});return{success:true}}
async function adminConfig({db,accessKey,expectedKey}){admin(accessKey,expectedKey);return{config:await config(db),rules:await rules(db)}}
async function saveConfig({db,accessKey,expectedKey,value}){admin(accessKey,expectedKey);await db.collection(CFG).doc("current").set({...value,enabled:value.enabled!==false,updatedAt:FieldValue.serverTimestamp()},{merge:true});return adminConfig({db,accessKey,expectedKey})}
async function saveRule({db,accessKey,expectedKey,id,hindi,displayOrder,active}){admin(accessKey,expectedKey);if(!String(hindi||"").trim())throw new Error("Hindi rule is required.");const ref=id?db.collection(RULES).doc(id):db.collection(RULES).doc();await ref.set({hindi:String(hindi).trim().slice(0,2000),displayOrder:Number(displayOrder||0),active:active!==false,updatedAt:FieldValue.serverTimestamp()},{merge:true});return{success:true,id:ref.id}}
async function deleteRule({db,accessKey,expectedKey,id}){admin(accessKey,expectedKey);if(!id)throw new Error("Rule id is required.");await db.collection(RULES).doc(String(id)).set({active:false,updatedAt:FieldValue.serverTimestamp()},{merge:true});return{success:true,id:String(id)}}
async function getPublicConfig({db}){const c=await config(db);return{config:c,rules:await rules(db)}}
module.exports={createApplication,findApplicationByMobile,getApplication,updateApplication,adminList,adminGet,stats,review,adminConfig,saveConfig,saveRule,deleteRule,getPublicConfig,downloadMedia};
