const crypto = require("node:crypto");
const { FieldValue } = require("firebase-admin/firestore");
const { getStorage } = require("firebase-admin/storage");

const APPS="pratibhaSammanApplications", CFG="pratibhaSammanConfig", RULES="pratibhaSammanRules";
const MAX_DOCS=10, MAX_IMG=3*1024*1024, MAX_FILE=5*1024*1024;
const MIME=new Set(["image/jpeg","image/png","image/webp","application/pdf"]);
const hash=v=>crypto.createHash("sha256").update(String(v||"")).digest("hex");
const mobile=v=>String(v||"").replace(/\D/g,"");
const date=v=>{if(!v)return "";const d=v?.toDate?v.toDate():new Date(v);return Number.isNaN(d.getTime())?"":d.toISOString()};
const admin=(key,expected)=>{if(!expected||!key||key!==expected)throw new Error("Unauthorized.")};
const config=async db=>{const s=await db.collection(CFG).doc("current").get();return s.exists?s.data():{enabled:true,opensAt:"",registrationLastDate:"",eventDate:"2026-10-25",title:"प्रतिभा सम्मान २०२६",description:"प्रतिभाशाली विद्यार्थियों के सम्मान के लिए आवेदन"}};
const rules=async db=>(await db.collection(RULES).get()).docs.map(d=>({id:d.id,...d.data()})).filter(r=>r.active!==false).sort((a,b)=>Number(a.displayOrder||0)-Number(b.displayOrder||0));
function windowOpen(c){if(c.enabled===false)throw new Error("Form submission is currently paused.");const n=Date.now();if(c.opensAt&&n<new Date(c.opensAt).getTime())throw new Error("Form submission has not opened yet.");if(c.registrationLastDate&&n>new Date(c.registrationLastDate).getTime())throw new Error("Registration is closed.")}
function validate(d, requireMedia=true){for(const k of ["name","mobile","address","city","state","pincode","motherName","fatherName","dateOfBirth","classStandard","schoolInstitute","achievementDetails"])if(!String(d[k]||"").trim())throw new Error("Required field missing: "+k);d.mobile=mobile(d.mobile);if(!/^[6-9]\d{9}$/.test(d.mobile))throw new Error("Invalid mobile number.");if(!/^\d{6}$/.test(String(d.pincode)))throw new Error("Invalid PIN code.");if(requireMedia&&(!d.facePhoto||!d.certificatePhoto))throw new Error("Face photo and certificate photo are required.");if((d.supportingDocuments||[]).length>MAX_DOCS)throw new Error("Maximum 10 supporting documents are allowed.");return d}
async function nextId(db){return db.runTransaction(async tx=>{const r=db.doc("pratibhaSammanMeta/counter"),s=await tx.get(r),n=(s.exists?Number(s.data().value||0):0)+1;tx.set(r,{value:n,updatedAt:FieldValue.serverTimestamp()},{merge:true});return "PS26-"+String(n).padStart(5,"0")})}
async function upload(f,id,type){if(!f?.base64)throw new Error("Invalid upload.");if(!MIME.has(f.mimeType))throw new Error("Unsupported file type.");const raw=String(f.base64).replace(/^data:[^;]+;base64,/,""),b=Buffer.from(raw,"base64"),max=f.mimeType==="application/pdf"?MAX_FILE:MAX_IMG;if(!b.length||b.length>max)throw new Error("File is too large.");const ext=f.mimeType==="application/pdf"?"pdf":f.mimeType.split("/")[1],path=`pratibha-samman/${id}/${type}-${crypto.randomBytes(5).toString("hex")}.${ext}`;await getStorage().bucket().file(path).save(b,{metadata:{contentType:f.mimeType,cacheControl:"private,max-age=300"}});return{path,name:String(f.name||"upload").slice(0,100),mimeType:f.mimeType,size:b.length}}
async function url(path){if(!path)return "";const [u]=await getStorage().bucket().file(path).getSignedUrl({action:"read",expires:Date.now()+15*60*1000});return u}
async function media(a){const x={...a};for(const k of ["facePhoto","certificatePhoto"])if(x[k]?.path)x[k]={...x[k],url:await url(x[k].path)};x.supportingDocuments=await Promise.all((x.supportingDocuments||[]).map(async f=>({...f,url:await url(f.path)})));return x}
function pub(d){return{applicationId:d.applicationId,status:d.status,name:d.name,mobile:d.mobile,email:d.email||"",address:d.address,city:d.city,state:d.state,pincode:d.pincode,motherName:d.motherName,fatherName:d.fatherName,dateOfBirth:d.dateOfBirth,classStandard:d.classStandard,schoolInstitute:d.schoolInstitute,achievementDetails:d.achievementDetails,otherAccomplishments:d.otherAccomplishments||"",overallPercentage:d.overallPercentage??null,facePhoto:d.facePhoto||null,certificatePhoto:d.certificatePhoto||null,supportingDocuments:d.supportingDocuments||[],review:d.review||null,clarification:d.clarification||"",createdAt:date(d.createdAt),updatedAt:date(d.updatedAt),submittedAt:date(d.submittedAt)}}
async function createApplication({db,data}){const d=validate({...data}),c=await config(db);windowOpen(c);const existing=await db.collection(APPS).where("mobile","==",d.mobile).limit(1).get();if(!existing.empty)throw new Error("A registration already exists for this mobile number. Please search the existing registration and edit it.");const rs=await rules(db);if(!Array.isArray(d.acceptedRuleIds)||rs.some(r=>!d.acceptedRuleIds.includes(r.id)))throw new Error("All active rules must be accepted.");const id=await nextId(db),token=crypto.randomBytes(24).toString("hex"),face=await upload(d.facePhoto,id,"face"),certificate=await upload(d.certificatePhoto,id,"certificate"),docs=[];for(const f of d.supportingDocuments||[])docs.push(await upload(f,id,"document"));const record={applicationId:id,accessTokenHash:hash(token),name:String(d.name).trim(),mobile:d.mobile,email:String(d.email||"").trim(),address:String(d.address).trim(),city:String(d.city).trim(),state:String(d.state).trim(),pincode:String(d.pincode),motherName:String(d.motherName).trim(),fatherName:String(d.fatherName).trim(),dateOfBirth:String(d.dateOfBirth),classStandard:String(d.classStandard).trim(),schoolInstitute:String(d.schoolInstitute).trim(),achievementDetails:String(d.achievementDetails).trim(),otherAccomplishments:String(d.otherAccomplishments||"").trim(),overallPercentage:null,facePhoto:face,supportingDocuments:docs,acceptedRulesSnapshot:rs.map(r=>({id:r.id,text:r.hindi})),status:"SUBMITTED",review:null,clarification:"",createdAt:FieldValue.serverTimestamp(),updatedAt:FieldValue.serverTimestamp(),submittedAt:FieldValue.serverTimestamp()};await db.collection(APPS).doc(id).set(record);return{application:pub(record),accessToken:token}}
async function authApp(db,id,token){const s=await db.collection(APPS).doc(String(id||"")).get();if(!s.exists)throw new Error("Application not found.");if(hash(token)!==s.data().accessTokenHash)throw new Error("Unauthorized.");return{s,data:s.data()}}
async function findApplicationByMobile({db,mobileNumber}){const normalized=mobile(mobileNumber);if(!/^[6-9]\\d{9}$/.test(normalized))throw new Error("Invalid mobile number.");const snap=await db.collection(APPS).where("mobile","==",normalized).limit(2).get();if(snap.empty)return{found:false};if(snap.size>1)throw new Error("Multiple registrations found for this mobile number. Please contact the coordinator.");const data=snap.docs[0].data();const token=crypto.randomBytes(24).toString("hex");await snap.docs[0].ref.update({accessTokenHash:hash(token),updatedAt:FieldValue.serverTimestamp()});return{found:true,accessToken:token,application:await media(pub(data))}}
async function getApplication({db,applicationId,accessToken}){const{data}=await authApp(db,applicationId,accessToken);return{application:await media(pub(data))}}
async function updateApplication({db,applicationId,accessToken,data}){const{data:old}=await authApp(db,applicationId,accessToken);if(["CONSIDERED_FOR_SAMMAN","NOT_SELECTED"].includes(old.status))throw new Error("Finalized applications cannot be edited.");const d=validate({...data}, false),c=await config(db);windowOpen(c);const rs=await rules(db);if(!Array.isArray(d.acceptedRuleIds)||rs.some(r=>!d.acceptedRuleIds.includes(r.id)))throw new Error("All active rules must be accepted.");const face=d.facePhoto?await upload(d.facePhoto,applicationId,"face"):old.facePhoto,docs=[];if(Array.isArray(d.supportingDocuments)&&d.supportingDocuments.length){for(const f of d.supportingDocuments)docs.push(await upload(f,applicationId,"document"));}else{docs.push(...(old.supportingDocuments||[]));}await db.collection(APPS).doc(applicationId).update({...d,name:String(d.name).trim(),mobile:d.mobile,facePhoto:face,certificatePhoto:certificate,supportingDocuments:docs,acceptedRulesSnapshot:rs.map(r=>({id:r.id,text:r.hindi})),overallPercentage:null,review:null,clarification:"",status:"SUBMITTED",updatedAt:FieldValue.serverTimestamp(),submittedAt:FieldValue.serverTimestamp(),accessTokenHash:old.accessTokenHash});return{success:true,status:"SUBMITTED"}}
async function adminList({db,accessKey,expectedKey,status="",filter=""}){admin(accessKey,expectedKey);const s=await db.collection(APPS).limit(500).get(),k=String(filter||"").toLowerCase().trim(),r=s.docs.map(d=>pub(d.data())).filter(a=>(!status||a.status===status)&&(!k||[a.applicationId,a.name,a.mobile,a.city,a.schoolInstitute].some(v=>String(v||"").toLowerCase().includes(k)))).sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt)));return{records:r,total:r.length}}
async function adminGet({db,accessKey,expectedKey,applicationId}){admin(accessKey,expectedKey);const s=await db.collection(APPS).doc(applicationId).get();if(!s.exists)throw new Error("Application not found.");return{application:await media(s.data())}}
async function stats({db,accessKey,expectedKey}){admin(accessKey,expectedKey);const s=await db.collection(APPS).get(),r={total:s.size,needsReview:0,selected:0,rejected:0,notSelected:0};s.forEach(d=>{const x=d.data().status;if(["SUBMITTED","UNDER_REVIEW","CLARIFICATION_REQUIRED"].includes(x))r.needsReview++;if(x==="CONSIDERED_FOR_SAMMAN")r.selected++;if(x==="REJECTED")r.rejected++;if(x==="NOT_SELECTED")r.notSelected++});return r}
async function review({db,accessKey,expectedKey,applicationId,status,overallPercentage,score,comment,clarification}){admin(accessKey,expectedKey);if(!["UNDER_REVIEW","CONSIDERED_FOR_SAMMAN","NOT_SELECTED","CLARIFICATION_REQUIRED","REJECTED"].includes(status))throw new Error("Invalid review status.");const p=overallPercentage===""||overallPercentage==null?null:Number(overallPercentage);const s=score===""||score==null?null:Number(score);if(s!=null&&(!Number.isInteger(s)||s<1||s>5))throw new Error("Score must be between 1 and 5.");if(p!=null&&(!Number.isFinite(p)||p<0||p>100))throw new Error("Percentage must be between 0 and 100.");await db.collection(APPS).doc(applicationId).update({status,overallPercentage:p,review:{score:s,comment:String(comment||"").slice(0,3000),clarification:String(clarification||"").slice(0,3000),reviewedAt:FieldValue.serverTimestamp()},clarification:String(clarification||"").slice(0,3000),updatedAt:FieldValue.serverTimestamp()});return{success:true}}
async function adminConfig({db,accessKey,expectedKey}){admin(accessKey,expectedKey);return{config:await config(db),rules:await rules(db)}}
async function saveConfig({db,accessKey,expectedKey,value}){admin(accessKey,expectedKey);await db.collection(CFG).doc("current").set({...value,enabled:value.enabled!==false,updatedAt:FieldValue.serverTimestamp()},{merge:true});return adminConfig({db,accessKey,expectedKey})}
async function saveRule({db,accessKey,expectedKey,id,hindi,displayOrder,active}){admin(accessKey,expectedKey);if(!String(hindi||"").trim())throw new Error("Hindi rule is required.");const ref=id?db.collection(RULES).doc(id):db.collection(RULES).doc();await ref.set({hindi:String(hindi).trim().slice(0,2000),displayOrder:Number(displayOrder||0),active:active!==false,updatedAt:FieldValue.serverTimestamp()},{merge:true});return{success:true,id:ref.id}}
async function getPublicConfig({db}){const c=await config(db);return{config:c,rules:await rules(db)}}
module.exports={createApplication,findApplicationByMobile,getApplication,updateApplication,adminList,adminGet,stats,review,adminConfig,saveConfig,saveRule,getPublicConfig};
